spring:
  data:
    redis:
      # ???
      database: 0
      # ??
      host: localhost
      # ??
      port: 6379
      # ??
      password: 123456
      # ???
      timeout: 5s
      # ????
      connect-timeout: 5s

  redis:
    redisson:
      # ??????: org.redisson.codec.JsonJacksonCodec
      codec: org.redisson.codec.JsonJacksonCodec
      # ?????????: ??????? * 2
      threads: 16
      # Netty?????????: ??????? * 2
      nettyThreads: 32
      # ????????: NIO
      transportMode: "NIO"
      # ???????????????????: 30000
      lockWatchdogTimeout: 30000
      # ??????????????: true
      keepPubSubOrder: true
      # Redisson ?????
      singleServerConfig:
        # ????????redis://host:port
        address: "redis://10.43.119.175:6379"
        # ??????: null
        password: 123456
        # ?????????: 0
        database: 0
        # ???????Redis????????????????: null
        clientName: null
        # ??????????????: 10000
        connectTimeout: 10000
        # ????????????????: 3000
        timeout: 3000
        # ????????????: 3
        retryAttempts: 3
        # ????????????????????: 1500
        retryInterval: 1500
        # ???????????: 32
        connectionMinimumIdleSize: 24
        # ?????????: 64
        connectionPoolSize: 64
        # ??????????????: 5
        subscriptionsPerConnection: 5
        # ???????????????????: 1
        subscriptionConnectionMinimumIdleSize: 1
        # ??????????????: 50
        subscriptionConnectionPoolSize: 50
        # DNS????????????????: 5000
        dnsMonitoringInterval: 5000
        # ????????????????: 10000
        idleConnectionTimeout: 10000