server:
  port: 48080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-security
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: NBfe@2099
    hikari:
      minimum-idle: 10
      maximum-pool-size: 10

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.macle.study.security

knife4j:
  enable: true
  setting:
    language: zh_cn
