
spring:
  task:
    execution:
      pool:
        coreSize: 5
        maxSize: 10
        queueCapacity: 50
        keepAlive: 10s
        allowCoreThreadTimeout: false
    scheduling:
      pool:
        size: 5
redis:
  host: localhost
  port: 6379

server:
  port: 8080

fixed:
  rate:
    in:
      milliseconds: 5000
